---
- name: set repo path
  set_fact:
    home_private_repo_path: "{{ my_projects_dir }}/home-private"

- name: my home-private repo is cloned
  git:
    repo: git@github.com:hoto/home-private.git
    accept_hostkey: yes
    update: yes
    dest: "{{ home_private_repo_path }}"

- name: folders for my configs are present
  file:
    path: "{{ home_dir }}/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - .ssh
    - .aws

- name: symlinks to my configs are present
  file:
    src: "{{ home_private_repo_path }}/{{ item.src }}"
    dest: "{{ home_dir }}/{{ item.dest }}"
    state: link
    mode: 0600
    force: yes
  with_items:
    - { src: '.ssh/config', dest: '.ssh/config'}
    - { src: '.aws/config', dest: '.aws/config'}
    - { src: '.grconfig.json', dest: '.grconfig.json'}
